### ISSUE TITLE
NoClassDefFoundError: androidx.media3.exoplayer.ExoPlayer$Builder

### ISSUE THREAD

**Issue by adam-adrian** [vfsfitvnm/ViMusic#37]
### Feature description

Add x86 Version for this app

### Why do you want this feature?

When I try to open the this app, it's just force closing

### Additional information

Handphone: Asus Zenfone 2 Android 6.0.1

**Comment by vfsfitvnm** [comment]
This app doesn't use native libraries, so there's nothing abi specific. Could you send the logcat?

**Comment by adam-adrian** [comment]
Sorry wrong info for other repo, but yes it force closing, I will send the logcat ASAP

**Comment by adam-adrian** [comment]
Here's the logcat: [https://drive.google.com/file/d/1NM0d_UJUYdzA3fJUmsXinHQzZWzyCwgO/view?usp=drivesdk](url)

I just open the app, is it correct?

**Comment by vfsfitvnm** [comment]
I cannot open that url. Could you paste the relevant logcat part here / load the .txt file here?

**Comment by vfsfitvnm** [comment]
```
06-11 19:17:17.120 E/AndroidRuntime( 3732): Process: it.vfsfitvnm.vimusic, PID: 3732
06-11 19:17:17.120 E/AndroidRuntime( 3732): java.lang.NoClassDefFoundError: f3.o
06-11 19:17:17.120 E/AndroidRuntime( 3732): 	at f3.r.<init>(SourceFile)
06-11 19:17:17.120 E/AndroidRuntime( 3732): 	at it.vfsfitvnm.vimusic.services.PlayerService.onCreate(SourceFile:7)
06-11 19:17:17.120 E/AndroidRuntime( 3732): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2917)
06-11 19:17:17.120 E/AndroidRuntime( 3732): 	at android.app.ActivityThread.-wrap4(ActivityThread.java)
06-11 19:17:17.120 E/AndroidRuntime( 3732): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1443)
06-11 19:17:17.120 E/AndroidRuntime( 3732): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-11 19:17:17.120 E/AndroidRuntime( 3732): 	at android.os.Looper.loop(Looper.java:148)
06-11 19:17:17.120 E/AndroidRuntime( 3732): 	at android.app.ActivityThread.main(ActivityThread.java:5480)
06-11 19:17:17.120 E/AndroidRuntime( 3732): 	at java.lang.reflect.Method.invoke(Native Method)
06-11 19:17:17.120 E/AndroidRuntime( 3732): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-11 19:17:17.120 E/AndroidRuntime( 3732): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by vfsfitvnm** [comment]
I could reproduce with Android 6.

**Comment by vfsfitvnm** [comment]
https://stackoverflow.com/q/70018748/16885569

**Comment by adam-adrian** [comment]
Yeah, sadly

**Comment by vfsfitvnm** [comment]
However I cannot reproduce with `androix.media3` `demo-session` app. [Relevant](https://stackoverflow.com/questions/70018748/crash-exoplayer-builder-in-android-version-5-and-6-android-api-21-and-23)

**Comment by vfsfitvnm** [comment]
Ok, I fixed it! Just wait for the next release!

**Comment by vfsfitvnm** [comment]
Bad news lol. It is solved, but there's an another error:
```
java.lang.NoClassDefFoundError: io.ktor.util.collections.ConcurrentMap$$ExternalSyntheticLambda0
        at io.ktor.util.collections.ConcurrentMap.computeIfAbsent(ConcurrentMapJvm.kt:19)
        at io.ktor.client.engine.cio.CIOEngine.selectEndpoint(CIOEngine.kt:119)
        at io.ktor.client.engine.cio.CIOEngine.execute(CIOEngine.kt:77)
        at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:95)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@8bbe0f9, androidx.compose.runtime.BroadcastFrameClock@20d83e, StandaloneCoroutine{Cancelling}@dd3269f, AndroidUiDispatcher@6a613ec]

```

**Comment by vfsfitvnm** [comment]
Nevermind, solved. The problem was these libraries used Java 8 language features, I had to enable [desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring)
