### ISSUE TITLE
Searching for a specific song crashes the app

### ISSUE THREAD

**Issue by ldsvrn** [vfsfitvnm/ViMusic#391]
### Steps to reproduce the bug

1. Open the app
2. Use the search button and search "little dark age"

### Expected behavior

List songs called little dark age.

### Actual behavior

The app crashes every time.

### Logs

type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221005.003/2022100300:user/release-keys
package: it.vfsfitvnm.vimusic:16
process: it.vfsfitvnm.vimusic

java.lang.IllegalArgumentException: Key gMEoi-mMMOw was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at c1.t.b(SourceFile:11)
	at s.s.b(SourceFile:2)
	at q.t0.a(Unknown Source:14)
	at k7.c.g0(SourceFile:6)
	at q.d0.a(SourceFile:26)
	at q.d0.M(SourceFile:3)
	at m.q0.M(SourceFile:32)
	at c1.v.c(SourceFile:17)
	at e1.s.f(SourceFile:10)
	at l.h.g(SourceFile:1)
	at l.h.L(SourceFile:53)
	at c1.r.z(SourceFile:2)
	at e1.f.n(Unknown Source:14)
	at e1.a0.f(SourceFile:5)
	at l.h.g(SourceFile:5)
	at l.h.L(SourceFile:56)
	at c1.r.z(SourceFile:2)
	at e1.f.n(Unknown Source:14)
	at e1.a0.f(SourceFile:5)
	at o0.h0.z(Unknown Source:5)
	at e1.f.n(Unknown Source:14)
	at e1.a0.f(SourceFile:5)
	at p.e0.z(Unknown Source:103)
	at e1.f.n(Unknown Source:14)
	at e1.a0.f(SourceFile:5)
	at e1.j0.a(SourceFile:8)
	at e1.j0.i(SourceFile:3)
	at a6.b.p(SourceFile:2)
	at l.w0.b(SourceFile:53)
	at l.w0.i(SourceFile:20)
	at f7.f.V0(SourceFile:3)
	at e1.h1.d(SourceFile:14)
	at e1.h1.c(SourceFile:2)
	at e1.n0.j0(SourceFile:24)
	at e1.g0.H(SourceFile:4)
	at e1.g0.I(SourceFile:5)
	at e1.s0.d(Unknown Source:7)
	at e1.s0.l(SourceFile:19)
	at e1.s0.h(SourceFile:4)
	at androidx.compose.ui.platform.AndroidComposeView.u(Unknown Source:15)
	at e1.d1.a(Unknown Source:3)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:21)
	at android.view.View.draw(View.java:23198)
	at android.view.View.updateDisplayListIfDirty(View.java:22062)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22018)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22018)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22018)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22018)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4579)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4290)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3517)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

### ViMusic version

0.5.0

### Android version

Android 13

### Additional information

The app crashed every single time. 
Searching for "little dark" gave me the expected results and did not make the app crash.

**Comment by Pentaphon** [comment]
No crash for me on Android 11

**Comment by ldsvrn** [comment]
I should have looked at the closed issues, it's a #387 duplicate
