### ISSUE TITLE
App Crash on Specific Search Queries

### ISSUE THREAD

**Issue by Shoptalky** [vfsfitvnm/ViMusic#436]
### Steps to reproduce the bug

1. Open ViMusic
2. Press Search button in bottom right
3. type "city escape" (or alternatively press the same query from history)
4. press enter

### Expected behavior

Return city escape songs

### Actual behavior

App crashes consistently. Searching "city escaoe" also caused a crash.

### Logs

Divest OS crash info feature:

```
type: crash
osVersion: [REDACTED]
package: it.vfsfitvnm.vimusic:16
process: it.vfsfitvnm.vimusic

java.lang.IllegalArgumentException: Key 49oLQQ6u2vE was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at c1.t.b(SourceFile:11)
	at s.s.b(SourceFile:2)
	at q.t0.a(Unknown Source:14)
	at k7.c.g0(SourceFile:6)
	at q.d0.a(SourceFile:26)
	at q.d0.M(SourceFile:3)
	at m.q0.M(SourceFile:32)
	at c1.v.c(SourceFile:17)
	at e1.s.f(SourceFile:10)
	at l.h.g(SourceFile:1)
	at l.h.L(SourceFile:53)
	at c1.r.z(SourceFile:2)
	at e1.f.n(Unknown Source:14)
	at e1.a0.f(SourceFile:5)
	at l.h.g(SourceFile:5)
	at l.h.L(SourceFile:56)
	at c1.r.z(SourceFile:2)
	at e1.f.n(Unknown Source:14)
	at e1.a0.f(SourceFile:5)
	at o0.h0.z(Unknown Source:5)
	at e1.f.n(Unknown Source:14)
	at e1.a0.f(SourceFile:5)
	at p.e0.z(Unknown Source:103)
	at e1.f.n(Unknown Source:14)
	at e1.a0.f(SourceFile:5)
	at e1.j0.a(SourceFile:8)
	at e1.j0.i(SourceFile:3)
	at a6.b.p(SourceFile:2)
	at l.w0.b(SourceFile:53)
	at l.w0.i(SourceFile:20)
	at f7.f.V0(SourceFile:3)
	at e1.h1.d(SourceFile:14)
	at e1.h1.c(SourceFile:2)
	at e1.n0.j0(SourceFile:24)
	at e1.g0.H(SourceFile:4)
	at e1.g0.I(SourceFile:5)
	at e1.s0.d(Unknown Source:7)
	at e1.s0.l(SourceFile:19)
	at e1.s0.h(SourceFile:4)
	at androidx.compose.ui.platform.AndroidComposeView.u(Unknown Source:15)
	at e1.d1.a(Unknown Source:3)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:21)
	at android.view.View.draw(View.java:22707)
	at android.view.View.updateDisplayListIfDirty(View.java:21579)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4531)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4251)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3374)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8793)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)

```

### ViMusic version

0.5.0

### Android version

Android 12

### Additional information

DivestOS custom rom used

I have checked https://github.com/vfsfitvnm/ViMusic/issues/387 but that was apparently fixed. This issue occurs on the latest version

**Comment by vfsfitvnm** [comment]
Don't worry! Unfortunately FDroid takes few days before publishing new updates :< (you can use the izzyondroid repo instead)
