### ISSUE TITLE
All songs dissapeared

### ISSUE THREAD

**Issue by SoMir0** [vfsfitvnm/ViMusic#984]
### Steps to reproduce the bug

Open app
Look up a song
App crashed
Songs are gone

### Expected behavior

My songs hould show up

### Actual behavior

I had 2 playlists, many offline songs, favorites, and they're all gone

### Screenshots/Screen recordings

![Screenshot_20230228-125223_ViMusic](https://user-images.githubusercontent.com/79478683/221846963-c7f17a05-1ba3-4e23-8c13-a2a8bb5b07eb.png)
![Screenshot_20230228-125219_ViMusic](https://user-images.githubusercontent.com/79478683/221846983-36993ffd-a1b3-4fc3-b0e4-c779b622b717.png)
![Screenshot_20230228-125212_ViMusic](https://user-images.githubusercontent.com/79478683/221846991-ab5d6f9a-f8c8-419b-b612-e41c4fd869f0.png)

### ViMusic version

0.5.4

### Android version

Android 10

### Additional information

It says the cache is still there, but nothing shows up.

**Comment by vfsfitvnm** [comment]
Could you paste the logcat here?
Tutorial: https://riptutorial.com/adb/example/14878/displaying-and-filtering-with-logcat
Command: `adb logcat it.vfsfitvnm.vimusic:*`

**Comment by SoMir0** [comment]
I don't think this is right - it keeps printing stuff, I can't even scroll all the way up

https://pastebin.com/cunr4ps2

**Comment by vfsfitvnm** [comment]
Would you try this one instead?
`adb shell "logcat | grep it.vfsfitvnm.vimusic"`

**Comment by SoMir0** [comment]
Now it doesn't show anything. Just to be clear, the app doesn't crash anymore, it crashed once and now all the music is gone, but it says the cache is still there.

**Comment by 8itlew7r** [comment]
I had the same issue as Bob. Here's the crash report from logcat, you can use Logcat Reader (https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_US&gl=US) to read it.

ViMusic v0.5.4
Device: Xiaomi M2006C3LG, Brand:Redmi
Android Target: 10.0 (SDK 29 Q)
Display: 720x1448 - xhdpi
CPU ABI: armeabi-v7a, armeabi

https://nopaste.ml/#XQAAAQCbdgAAAAAAAAAeaAQNhvNGQKSUW/nyI4EKXY7oXQYkvxiGtH95aejPYGx8LJoAT/4NNfGZSQllFkjzeF+JxDHT2eFI7LMXlB1Q1is/FnNBCNn6E3Cq0Qs/1ERWzMp7PsP3NmfB8Kdk4tcQPkDxL3KZp+x02UdZdLZFyZK/CNNUzHTv8gjGW/WL+9U5RwINzSyUynCl7WkOZwh2qqoPKG28e3+GjuafrkE6o2sopkrObjnU6SQHDbtoK24DPgAoC/d17btPDvUj8f3WE3l8Opzohd4GlAep+alIjLa8RR+CcQvdSpDdMgd+gDzvfhZRA3efHV3cIGCsSIF8kDTQXUYcZMF+nQWH/kD0vNAXfbg4UNbBUY3QvsCA3FvR8O5w9Q1gYpu1w/nd3U1GwlcOY4G6/MZ76D8m2O58aj3QLmcHB6r7LK3rhmufTROii5uorHH3pE+yTSEjaBOqstLffpYlz/HuyIHYPPIasy6ujSuwIBn+PO0lopqTzX9e/1tAISBM3VEmWbc/gAtSenSfgi7fSCWp1p54qDbAiJzwQSh7bx9W/LHCmXwpf/jZchAkcKrPw37QcVFoQw0NHeMEm6iNqkWdJReyyvq3AzfrNP6hJvgKx9sLBzf5BXqf+VBWcuhW8CprF3x8rHhLJIQNBH1Ery4H7+d4W40B3Z5/gVoZf7k4v3ttO8+cg2lZ/a3HWHsps2syhP/0X+xe956Izbf1++12en2v/gC6UUkPONKNjeX6nQGtTBm0lhJr9GlYSyakF4CoYwTrHce4J9aCYKzlXwIYQmK7TmakXzEwhAYe+N0apbdhLsRTObNmZjKrJR/FiRVVT/+2/igQr47s5buzX0fGlSmrhlTdjHplULFBUW1sj0tV8H+8gKy0VZnXkggdiwuzjN9GecmTIBfzWhTvcvfG8HA9Ei8eyhvClrCxSELVzM7bfjV+lgI269hWEtXX+qqR6TFye/YT4CvqSmaLOVavOH1eBC1013MSYqb748nvpnFwLZWuOxkK7dy6mal5yraPrLLR9YKS9bi6NIuuM8vEJq73QGDjhG5pmdCVRaLkox21ivlBIVoj0pyYVXbUtvTrMzFrY1kV7yCe5bgI7NoxHYKmUh3xjFxhX990IDt9VEHD8jx+sPZW4P+ysVw6jNOKrXeIopzvfte4l8K+XnxOxbapHwzYBx9itIuoZRi3hAtVghzIqASUnirHH/AM6T89imT2K79xW9WJuzfiCK80T/dLnMaU0gzxVTn6yU8ZeUAHRyjaJ2uMGBsCZdmmkjc5XP1tsBN9PVmx/2SUoHMULBuy6GR80E4KEhDKNlnHweNZBPbr/U2vPeDGjZLUzeLwiJKUOKGUeQMunvzF3M0kGr8tJ3PeAmpbBT6pN1k6eoYeXRKTJedHrhdeuJoq3+SU9EPvCJDzEJ9x3IgEVLF0ihKFEDgCwfeEG+lUxt+pp+9eIKOsAu+aanliWUtnP+qQJXqJ2Gtc9NYG5Bp7tnlAZxT/uXpJjE7BT1Iw2jD68Vuq3WqwwB4UviUMb21JBXti6C6E0SfzSBxw6veYi6nIRzSvyqnmm2Pc3oHk1vyqP49SoPFzRlEbIHnBKFUQ6yP4SKNadHv8VfwZ+0wnHEWux2LY82wGqY7u5nLU+8MtKJ07+FERvE/ZVgL2KwPEr/CW37+1lK/zLxd6Nm6rdv68PmutqOvVx1VspPffzemW0yPfjugQQTW4bV0haYgSPIGbAG/WyaKSa80lAV1NH9f/RdRplyhlYDQv/yGBVHNwZJPASMRz/8IJWxtnKqoblyuxjNlZAqzesFIr0F2NWwH8CW5r4O37aBSGnpelDdPzHN1FSKUy+p1zMBV3JSK4KYLeiLZBBwa33kBMlBDdAzoKzzZP68ewkVbYUwLpLSSm2AFI+8NOCLE9DEkZvl8Ihng8A3QAUKn1h0ZVMFTrZ7Bd6eDZpKDYwlubKq47wzJ6mefSe0+hvnuz17v2BvzZ+BvvXCDj00Ek1QuyMvJS62t7+O85qsiPwY/5eqGVJiq2Fl5BDpeKba8tEmHcXALgq+BSmba6GL9hMlZDHdln1ZGtvW7xIHb14JBO0h+y2GR7k0lPuT6XPN5juDaa+9DjQBH4FyLGpgFf2jWky8jEASfEd81wZ1p8hiV0scZpqqybv3kYUS7iv36nfPr4jcTwJhjRG5KjQEWPIDh/p8XqGDGpUb5MawPrR/fxIG9likmJFOS5ndhsWRnRaHh9etzjqci7GiRmHkqec3PKsdQSnb8C9GMFFeg+/CtRNVHH8b3aSUFTj1Z1H/0ig1SDMLSOlplv/5qn+3RulDMXreDxF6JC7vXPvjYFR9vC7sy6Ov9OZlt8RM8EjcJ55fpX1BaFJlPdL69NYPsm8u5KLkGhRaAO17eJFZ5a75f0dzQs2sKujA5E3czkN70J5D2PldeptHvK5pmUrdyZ1XyO3OkyyHTSdYBQBpZ8TJwATxoqt0Ev2gsYT6j7W7tGv58mrXFhmf30kO8hY3ZpLbW5G1p9ugiJDlD26k2fH/1uSkIGbuz0i+AJzkZfc2GCutF3WjROihUJiyyxmrtWAkVlOIeEfjGoVTztj3E7NFmikcOME+lQwCJ6EHzkLsoV1wxkzXlUlFxkkQLeMrVP6v5zQYVlbpSG28P/G5Res7X/9A+DIrJiCOBMqe0CG+rjovLv6+vwAYb34JibkgymKRN+6lZSfM+EI9yMSs3mgDRSw0vC/K23n7rsNBeSLFdLI1M5RdWHRKhqbFSHknNItT+G3KXtQal0CLpBk84ZXQZgO+GESMphjPus16t3JFu+RTo/fy3w7x9xFRsnXTjnNC+hxtOtGmkSYd94Id0qo7VtrQQuIOPeuIaQoNRN8IauBo1XYF4A7E2nWMSM/Pp2Ni5h3NyQK1buvnOm5en3vFB3QYcR4u94W0ZfYtDuUUK4vwvQ5tI9rFONkufAp/YKYq9EWx9wuXf8uZN871pnUtPaQhkZvZnwbx0A41Wkx3axfZLYyY6bduRV8xsMYHKssmZjfd2F93Ip04LZTULBF8inFwghT1HyRDFViAaZRrWE9OCEk6jt2XdA9RJ6rPRTU2rP+thaHrLipCIUFJw39Ut52HpAR39tPJawR0YBJhpbm/xfR1sqPb4jjHy7ansle6qUgLq9emDSCakLTvkb/5Jth5XWiIpIH1wyELNYCUxQYReQhpiGjOMdQVOzvlQSOc76jiI9sIFCEPPig35/VLIlgYI68BnKv242/emmHE1alnLpC/TfS3VoxUFPARd6+Sg+cLde7wN6XM6lQtL+SA/RKuPcXA4pIA/qqABg+naaZD/Ny1Soi/6vcS+U+yNHdzg76SfWbj171TpG+PkDIfD2Bs2c6RpCRqtwIrXwevYvQjgiONMl87LwBGN/9MPgQyr4c2Yt24Ezgq4GcifHuYobMNvKB1XEea1oAAQ31LyKVPAHc+0OUiUT46rcAO16NA2mwAV7hlMw4ljrK2ynmz3//luDyiYaVRMz7XLLoj3Lx36wpqdeoNkQvU0x6XKAtK3EC8XjS60KITd89/H8EknUZYNWLlTKsF7iGkCrUSlCEJ4XrELsbZw0MiaoU7ATW0bXAdxiQud5uxkjZHL8CpeNdJUGCc9y5ucB3Sk1y222H5NaUMpQZybxz6z7+SN75XKYo6zYzEfStKoxyM1h0kJL48jeQqDUXtBgI++Bp9uRjbistGDpJmCYV5J5DGwWNLkwtaAYcx0uFIoSyyUbU25sphpc/YMzeEbEdlU2TeuafPJZVfrPlxDMMfCZ+U4oQAOjhmjihXfsPVsT66YouhvajpRf4OYkU8pazplczqZumFA18qRg0RIHXqYqZWwhYaALsv81OKo7Rh9wQNvEmezf1/4SZQ5voWWQIzG7ODlJqFislZNvlQtpmp8WfRQo11o65g3zQJeqnDjua3LFaRcAwn4KoFa3yyMrX/p3ducbWqeaqKpVcWkMlclCurysO8T32HfLOAhPz2/DbPZUOK7v8pWGuD6bIA2ChBTpOUoTyyhzDWF2G9zepQKAG+9CNL/dJh3jACMFI6YchyErVXe6GU2dn8EuNWsp8JY7swhtVpIFtKfeC44d7RgxrsUnCyt+NKOCDSsO2HJbrje9MVuqUClqVYDvqBmPhLTn49aETmlP6UiCrIBkFEOydQfZljS1iLJvKNwjl+rey+JLLmA+qddsKVlTuLn+G/N4u5jqffnCm2hIGViKlPD7EgX/vW55qfcZRBPKO9TcPhbD5uJyYg130ttrBzySxo07ZV1Xroksi1gkg+xd4Wh6zNpSpEQcUHkOKXiZ44mkOK0inN6qP4msicxGQmpg3DuY66Ts5uKuDbNcpk1jgLgcZmuBIc9hzj1dB3d6IllLgIb/4osVQUUk8IgdvY1/xZHXOs3QsZt6U51NgKJRuZ3kXYskNOqTIH/DCcFRC81AGSdPDhPIkpCzwmVt8iCd77iX0TtBYjEJJpXAhHiVVXft4dIqced6dThTLy+wnnU+X5VdnFRswFpLsnyXM6Ga+kOX0HK4hwtXzunX9PSlwHHrw4c5SF6M/xfFhrKAySWtdvX+Z7CoUBELDFsY01Fjw1d1Hyxmg8q7r51wFTmUGZOrF6PYULbM7gqFx5hMnkA8lcApwl+ZbDoO/L5MRQepyyvC3U7H5tF6FLTHY3CJClAl4jSnbxHzvJPfYNwr4NwNdg6sDHSBVUkljJf+30LLL4XSg0zEPl3uRdC60CtSg2elvutAyTWs+T0UYb0UjcNPuQb6l0rGfoba8m7SSRnm6BFFdNzVVao22ti4ybFXpaBiQoKx8iA17FAypRMBjO4spX/2u45MdpyQ6E3qfJWkTelkH0r1hgUDrrLhm8w1Gj6lsX2AN62xkOWL0CsdUDjXThoiQP92hye0vIbTguZspGE6f+/qoRqbHNeDh+jbR1Xs1XZuaHxoIjK1FY0gef4/NPfKh2qRL6bazaQBvEV9bJQpaZWNQACOwKQLAe74Q8PEVDrluRjaucmUWLtL/Digs8fZlLWdPURHsbUaQuPkeHjlbEd96POTQIDh+GWCea7X4j2fo8v+tXZUUAwg0liaxZsRGSbwkk3hJ8A840gTJoOkwSnYHWRP1iu0pqGsPr9eaYgxonhkxxcON9XwDlDmrWgCkwkFEkcMIGMXiU3G2ztxBUQEfPoqswDHv0ugo3FSEj91kiFOrabs7O9BmleATuQAW9ITkQW1zV2PH+xa8ID/PyZtjf1xeWta+oLyVDVPb/bN7RtWUKWiXC+mf2vwsBZIPUAoCRLsaEpKkBIkKcVUN6R4390RENinIoqjz+05sFXR0/oAJfaMEwAhA/91rFUFKBpUjLWxTXIrn16DzqFysBX9VLQHqb+zM+0B7BCq6SKGIR9gCwNsgkcRSceD++9aBm+8Atu9H/r7W2dQge3h8i2//FIT55656FcG8DCqURA5ppCY6eoyFIlXsGAu8MQajjr1M56DwblNc49FHfyVxykIahOAsxYbT+zNkml9y0YwxRE80QI6jfA+g01NIQhyTfUgW/clCG1U//XmIWhBt/6z/TY=

**Comment by vfsfitvnm** [comment]
@8itlew7r Thanks, that's helpful. There are **three** crashes, actually. I think the one which caused the database to be erased is the following:
```
java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
	at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:917)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:400)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:585)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(FrameworkSQLiteDatabase.java:2)
	at androidx.room.RoomDatabase.j(RoomDatabase.java:9)
	at androidx.room.RoomDatabase.endTransaction(RoomDatabase.java:0)
	at it.vfsfitvnm.vimusic.Database_Impl.insert(Database_Impl.java:0)
	at it.vfsfitvnm.vimusic.Database$Companion.insert(Database.java:12)
	at it.vfsfitvnm.vimusic.Database$DefaultImpls.insert$default(Database.java:0)
	at it.vfsfitvnm.vimusic.service.PlayerService$createDataSourceFactory$1$urlResult$2$1$3.invoke(PlayerService.java:0)
	at it.vfsfitvnm.vimusic.service.PlayerService$createDataSourceFactory$1$urlResult$2$1$3.invoke(PlayerService.java:0)
	at it.vfsfitvnm.vimusic.DatabaseKt.query$lambda$0(Database.kt:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

The others are:
```
java.lang.SecurityException: Caller it.vfsfitvnm.vimusic:1411374 cannot post for pkg it.vfsfitvnm.vimusic in user 14
	at android.os.Parcel.createException(Parcel.java:2074)	at android.os.Parcel.readException(Parcel.java:2042)
	at android.os.Parcel.readException(Parcel.java:1990)
	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:2776)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:497)
	at android.app.NotificationManager.notify(NotificationManager.java:447)
	at android.app.NotificationManager.notify(NotificationManager.java:423)
	at it.vfsfitvnm.vimusic.service.PlayerService.onEvents(PlayerService.java:0)
	at androidx.media3.exoplayer.ExoPlayerImpl.lambda$new$0(ExoPlayerImpl.java:0)
	at androidx.media3.common.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:0)
	at androidx.media3.common.util.ListenerSet.handleMessage(ListenerSet.java:0)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.notification.NotificationManagerService.resolveNotificationUid(NotificationManagerService.java:5088)
	at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:4778)
	at com.android.server.notification.NotificationManagerService$10.enqueueNotificationWithTag(NotificationManagerService.java:2410)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1064)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
```
and
```
java.lang.IndexOutOfBoundsException: Index -1, size 1
	at androidx.compose.foundation.lazy.layout.MutableIntervalList.checkIndexBounds(MutableIntervalList.java:0)
	at androidx.compose.foundation.lazy.layout.MutableIntervalList.c(MutableIntervalList.java:1)
	at androidx.compose.foundation.lazy.layout.DefaultLazyLayoutItemsProvider.c(DefaultLazyLayoutItemsProvider.java:5)
	at androidx.compose.foundation.lazy.LazyListItemProviderImpl.getKey(LazyListItemProviderImpl.java:2)
	at androidx.compose.foundation.lazy.layout.DefaultDelegatingLazyLayoutItemProvider.getKey(DefaultDelegatingLazyLayoutItemProvider.java:8)
	at androidx.compose.foundation.lazy.LazyListItemProviderKt$rememberLazyListItemProvider$1$1.getKey(LazyListItemProvider.kt:2)
	at androidx.compose.foundation.lazy.LazyMeasuredItemProvider.a(LazyMeasuredItemProvider.java:7)
	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-nXYdgZc(LazyListMeasure.kt:0)
	at it.vfsfitvnm.compose.reordering.ReorderingLazyListKt$rememberLazyListMeasurePolicy$1$1.invoke-0kLqBqw(ReorderingLazyList.kt:0)
	at it.vfsfitvnm.compose.reordering.ReorderingLazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(ReorderingLazyList.kt:0)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$1$2$1.invoke-0kLqBqw(LazyLayout.kt:0)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$1$2$1.invoke(LazyLayout.kt:0)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(LayoutNodeSubcompositionsState.java:0)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.java:0)
	[continues]
```

Not sure how I could reproduce them, to be honest :/

**Comment by 8itlew7r** [comment]
> Thanks, that's helpful.

I don't know how to like or thumbs up your comment, but I'm glad I could help, and I hope it helps solve this problem because it just removes my old songs, which is not that big a deal.

**Comment by vfsfitvnm** [comment]
>  it just removes my old songs, which is not that big a deal.

@8itlew7r oh, maybe your problem is different (the stack trace is still helpful btw) - OP said the application crashed and - when it was reopened - the data got completely erased.

**Comment by 8itlew7r** [comment]
> @8itlew7r oh, maybe your problem is different

I'm sorry, the words I used are confusing.

> OP said the application crashed and - when it was reopened - the data got completely erased.

But no, I think we have the same issue and the data isn't completely erased because cache is still there, but like the OP said, nothing shows up.

Anyway, I won't waste any more of your time; I know you've got this!

**Comment by saurabhtiwari28** [comment]
Same problem, I faced

**Comment by Jarletoss** [comment]
The same thing happened to me today! A 1200 song playlist + offline songs disappeared when the app crashed today, i hope theres a fix soon cause im going on a long trip in a few days and music is my everything on long rides

**Comment by Jarletoss** [comment]
Same thing happened to me, hope this gets fixed soon

**Comment by ikanakova** [comment]
I think this could be solved if the application have been creating an automatic backup.  We would then lose a few songs at most, but not everything.

**Comment by 8itlew7r** [comment]
So I just noticed that after listening to songs in the default offline playlist because I don't have Wi-Fi, the database gets corrupted again, so maybe there is a pattern going on? I've been using your app for a few months now, but this only happened after listening offline for a long time.

**Comment by vfsfitvnm** [comment]
If you have a backup hanging around (and, most importantly, you are still using this app after this embarrassing problem), you can recover it via:
```
sqlite3 corrupted.db ".recover" | sqlite3 recovered.db
```

**Comment by 8itlew7r** [comment]
It crashes again but I had the logcat of the pid, I'm hoping it might help.

Log file: https://tny.lv/logcat
Password: https://tny.lv/logpass

**Comment by 8itlew7r** [comment]
I've noticed that everytime my phone is low on storage the offline songs disappear, maybe that's when corruption is triggered?
